In [60]:
# Importing Libraries
import pandas as pd

# Declaring Data Path
dirPath = "../../Input Data/Split Time Points"

# Initializing a diction of split times
timeSeries = {}
for visit in range(1, 6):
    timeSeries[visit] = pd.read_csv(f"{dirPath}/Soma plus MGH repeat measures (T{visit}).csv")

In [61]:
# Initializing the output file
preREFX = timeSeries[1].copy()
postREFX = timeSeries[4].copy()

# Altering time signature on sampleID
for index in range(len(preREFX.index)):
    preREFX.iloc[index, 0] = f"{preREFX['SampleId'][index][:-2]} (T1-T3)"

for index in range(len(postREFX.index)):
    postREFX.iloc[index, 0] = f"{postREFX['SampleId'][index][:-2]} (T4-T5)"

# Displaying modified output files
display(preREFX.head(1))
display(postREFX.head(1))

,SampleId,VDR,NCF-2,TERF1,FOXM1,FANCL,CBS,PIAS4,IL-10 Ra,STAT3,...,tuningfork_noninj,pa_scale_rank,age_enrollment,height,weight,age_menarche,hx_fx,hx_stfx,vitd,pth
0,SFX02 (T1-T3),1784.9,821.3,842.0,730.9,811.2,2536.8,934.7,2481.8,8230.6,...,Negative,NaN,24.2,168.0,63.3,13.0,Yes,Yes,38.745,21.5

,SampleId,VDR,NCF-2,TERF1,FOXM1,FANCL,CBS,PIAS4,IL-10 Ra,STAT3,...,tuningfork_noninj,pa_scale_rank,age_enrollment,height,weight,age_menarche,hx_fx,hx_stfx,vitd,pth
0,SFX02 (T4-T5),1464.6,993.7,896.4,948.2,876.4,2103.3,825.1,2273.4,14604.9,...,Negative,6.0,NaN,167.8,73.0,NaN,NaN,NaN,41.086,OCL

In [62]:
# Retrieving the column names
col_names = preREFX.columns.tolist()
col_names.remove("visit")
col_names = col_names[1:1513]

In [63]:
# Averaging by indexing through the time points – Pre-refracture
for feat in col_names:
    for row_index in range(len(preREFX.index)):    
        col_index = preREFX.columns.get_loc(feat)
        average = (timeSeries[1].iloc[row_index, col_index] + timeSeries[2].iloc[row_index, col_index] + timeSeries[3].iloc[row_index, col_index]) / 3
        preREFX.iloc[row_index, col_index] = average

In [64]:
# Averaging by indexing through the time points – Pre-refracture
for feat in col_names:
    for row_index in range(len(postREFX.index)):    
        col_index = postREFX.columns.get_loc(feat)
        average = (timeSeries[4].iloc[row_index, col_index] + timeSeries[5].iloc[row_index, col_index]) / 2
        postREFX.iloc[row_index, col_index] = average

In [67]:
# Displaying modified output files
display(preREFX.head(1))
display(postREFX.head(1))

# Saving to directory
outPath = "../../Input Data/Averaged Time Points (Pre:Post Refracture)"
preREFX.to_csv(f"{outPath}/Soma plus MGH repeat measures (AVG T1-T3).csv", index=False)
postREFX.to_csv(f"{outPath}/Soma plus MGH repeat measures (AVG T4-T5).csv", index=False)

,SampleId,VDR,NCF-2,TERF1,FOXM1,FANCL,CBS,PIAS4,IL-10 Ra,STAT3,...,tuningfork_noninj,pa_scale_rank,age_enrollment,height,weight,age_menarche,hx_fx,hx_stfx,vitd,pth
0,SFX02 (T1-T3),1607.766667,908.366667,849.366667,812.9,827.166667,2466.5,841.266667,2301.7,10190.533333,...,Negative,NaN,24.2,168.0,63.3,13.0,Yes,Yes,38.745,21.5

,SampleId,VDR,NCF-2,TERF1,FOXM1,FANCL,CBS,PIAS4,IL-10 Ra,STAT3,...,tuningfork_noninj,pa_scale_rank,age_enrollment,height,weight,age_menarche,hx_fx,hx_stfx,vitd,pth
0,SFX02 (T4-T5),1484.6,933.1,885.4,987.4,877.8,2127.1,811.2,2208.6,13643.7,...,Negative,6.0,NaN,167.8,73.0,NaN,NaN,NaN,41.086,OCL